    git branch -D EPC-1790/unit-test-group-pelayanan
    git branch -D EPC-1791/grouping-unit-test
    git branch -D EPC-1794/grouping-unit-test
    git branch -D EPC-1797/grouping-unit-test
    git branch -D EPC-1811/gin/pasienterdaftar
    git branch -D backup_regresi/18-des-2025
    git branch -D feature/enhancement-ci-cd-unit-test
    git branch -D feature/global-skrining-lab
    git branch -D feature/regres/23-des-2025
    git branch -D hot-fix/e-clinic-ng/resep
    git branch -D hotfix-unit-test
    git branch -D hotfix/asset-css
    git branch -D merge/epc-1833-epc-1777
    git branch -D mock/EPQ-725
    git branch -D new-fix-bug
    git branch -D pelayanan-non-medis-frontend
    git branch -D research-aggregate
    git branch -D research-request-laporan
